### ISSUE TITLE
Ошибки запуска и при тестировании функции snapshot-disks в cloud function

### ISSUE THREAD

**Issue by warsconstar** [nikolaymatrosov/go-yc-serverless-snapshot#3]
**При запуске теста:**
`{
    "errorMessage": "user code execution causes panic: runtime error: index out of range [0] with length 0",
    "errorType": "UserCodePanic",
    "stackTrace": [
        {
            "function": "runtime.gopanic",
            "file": "/function/runtime/src/runtime/panic.go",
            "line": 965
        },
        {
            "function": "runtime.goPanicIndex",
            "file": "/function/runtime/src/runtime/panic.go",
            "line": 88
        },
        {
            "function": "github.com/nikolaymatrosov/go-yc-serverless-snapshot.SnapshotHandler",
            "file": "/tmp/gopath/src/function/code/snapshot-disks.go",
            "line": 38
        },
        {
            "function": "reflect.Value.call",
            "file": "/golang/src/reflect/value.go",
            "line": 476
        },
        {
            "function": "reflect.Value.Call",
            "file": "/golang/src/reflect/value.go",
            "line": 337
        },
        {
            "function": "bb.yandex-team.ru/cloud/cloud-go/serverless/runtime-artifacts/runtime/golang/base/rt.getHandler.func2",
            "file": "/app/src/bb.yandex-team.ru/cloud/cloud-go/serverless/runtime-artifacts/runtime/golang/base/rt/handler.go",
            "line": 147
        },
        {
            "function": "bb.yandex-team.ru/cloud/cloud-go/serverless/runtime-artifacts/runtime/golang/base/rt.FunctionHandler.Handle",
            "file": "/app/src/bb.yandex-team.ru/cloud/cloud-go/serverless/runtime-artifacts/runtime/golang/base/rt/handler.go",
            "line": 31
        },
        {
            "function": "bb.yandex-team.ru/cloud/cloud-go/serverless/runtime-artifacts/runtime/golang/base/rt.(*Runtime).handleSingleRequest",
            "file": "/app/src/bb.yandex-team.ru/cloud/cloud-go/serverless/runtime-artifacts/runtime/golang/base/rt/runtime.go",
            "line": 39
        },
        {
            "function": "bb.yandex-team.ru/cloud/cloud-go/serverless/runtime-artifacts/runtime/golang/base/rt.(*Runtime).Start",
            "file": "/app/src/bb.yandex-team.ru/cloud/cloud-go/serverless/runtime-artifacts/runtime/golang/base/rt/runtime.go",
            "line": 22
        },
        {
            "function": "main.main",
            "file": "/app/src/bb.yandex-team.ru/cloud/cloud-go/serverless/runtime-artifacts/runtime/golang/base/bootstrap.go",
            "line": 27
        },
        {
            "function": "runtime.main",
            "file": "/golang/src/runtime/proc.go",
            "line": 225
        },
        {
            "function": "runtime.goexit",
            "file": "/golang/src/runtime/asm_amd64.s",
            "line": 1371
        }
    ]
}`

**В логах функции:**
`ERROR RequestID:  Code: 502 Message: Error during function invocation
{"errorMessage":"rpc error: code = InvalidArgument desc = Request validation error: Name: invalid resource name","errorType":"UserCodeError"}`

**Comment by nikolaymatrosov** [comment]
Какую функцию и как вы запускаете? Очевидно, что вы не формируете корректный event-объект, который функция ожидает на вход.

**Comment by warsconstar** [comment]
snapshot-disks в Cloud Functions
задеплоил, согласно вашей инструкции(в .env все заполнил)

**Comment by nikolaymatrosov** [comment]
Вы же ее не из вкладки Тестирование в веб-редакторе запускаете, так? Если же все-таки оттуда, то, пожалуйста, как я уже писал выше, сформируйте корректные данные, которые будете подавать на вход. Так же советую перечитать README, там описана архитектура решения.
Еще хотел бы уточнить, что код распространяется под лицензией MIT.
