### ISSUE TITLE
Падает скрипт snapshot-disks из-за некорректного формирования имени снимка

### ISSUE THREAD

**Issue by it1804** [nikolaymatrosov/go-yc-serverless-snapshot#4]
Нашел интересный баг: по неизвестной мне причине не заполняется поле d.Name при формировании таски в очереди, то есть остаётся пустым. 
https://github.com/nikolaymatrosov/go-yc-serverless-snapshot/blob/7866d84d9c71d59b38e73069f66ca8f509dd134f/spawn-snapshot-tasks.go#L80

И из-за этого c ошибкой падает скрипт snapshot-disks.go. Проблема в этой строке, из-за того что имя диска было получено пустым из очереди, формируется имя снепшота с тире на конце, что похоже запрещено, и операция создания заканчивается неудачей. В веб-консоли также не даёт создать имя снепшота с тире на конце.
`snapshotName := "snapshot" + "-" + expirationTs + "-" + createSnapshotParams.DiskName`

PS
`yc compute disk get <id>` также в выводе команды не увидел имени диска.

На виртуальной машине диск один, имя диска в веб-консоли совпадает с id, способа изменить имя не нашёл. 
Возможно были изменения в api, после которых убрали возможность работать с именем диска.

**Comment by nikolaymatrosov** [comment]
Пришлёте pull request с исправлениями?

**Comment by it1804** [comment]
> Пришлёте pull request с исправлениями?
Упс, не заметил поле в веб-консоли где можно прописать имя, причём на самом видном месте. мои извинения за ложную тревогу.

Внес изменения, чтобы 
1. использовать идентификатор диска если имя не прописано в настройках, чтобы не потерять приндлежность снепшота к конкретному диску
2. устранить сбои в таких ситуациях с дефисом на конце строки для предсказуемого выполнения скрипта

**Comment by nikolaymatrosov** [comment]
Спасибо
